#©2016-2017 EdgeVerve Systems Limited (a fully owned Infosys subsidiary),
#Bangalore, India. All Rights Reserved.

buildlinux:
  stage: build
  script:
    - export ACTIVITI_HOST=https://activiti.oecloud.local
    - npm config set registry http://10.188.25.62:9009
    - npm config set fetch-retries 0
    - npm install --no-optional
    - export NODE_ENV=docker
    - export MONGO_HOST=10.73.53.144
    - export DB_NAME=${CI_PIPELINE_ID}_mongo
    - node tools/cleandb.js
    - ./node_modules/.bin/grunt eslint-test-coverage
  after_script:
    - export MONGO_HOST="10.73.53.144"
    - export DB_NAME=${CI_PIPELINE_ID}_mongo
    - node tools/cleandb.js
  tags:
    - CEP_RUNNER
